
<ExampleButton>:
	FlexLayout:
		FlexLayout:
			orientation: "horizontal"
			FlexButton:
				text: "text1"
				on_release:
					print(self.text)
		FlexLayout:
			orientation: "horizontal"
			FlexButton:
				text: "<- splash"
				on_release:
					Window.set_title("splash")
					app.root.current = "splash"
			FlexButton:
				text: "label ->"
				on_release:
					Window.set_title("label")
					app.root.current = "examplelabel"